#!/bin/bash
set -uo pipefail
# NOTE: no `set -e` — we don't want one failed iteration to kill the loop

# ─── autodesign.sh ────────────────────────────────────────────────────────────
# Autonomous design iteration loop. Each iteration runs in a fresh Claude
# subprocess — no context bleed between iterations.
#
# Generated by /autodesign during preflight. Edit as needed before running.
#
# Usage:
#   bash .autodesign/autodesign.sh
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUTODESIGN_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$AUTODESIGN_DIR")"

# ─── Config (set by preflight) ────────────────────────────────────────────────
TARGET="${TARGET:-}"
CAPTURE_METHOD="${CAPTURE_METHOD:-playwright}"
DEPLOY_CMD="${DEPLOY_CMD:-}"
MAX_ITERATIONS="${MAX_ITERATIONS:-5}"
CONVERGENCE_THRESHOLD="${CONVERGENCE_THRESHOLD:-2}"
EXPLORATION_ENABLED="${EXPLORATION_ENABLED:-false}"
EXPLORATION_COUNT="${EXPLORATION_COUNT:-10}"
FIGMA_FILE_KEY="${FIGMA_FILE_KEY:-}"
AGENT_RUNTIME="${AGENT_RUNTIME:-claude}"

# Load config.json overrides if present
CONFIG_FILE="$AUTODESIGN_DIR/config.json"
if [[ -f "$CONFIG_FILE" ]] && command -v python3 &>/dev/null; then
  _cfg() { python3 -c "import json,sys; d=json.load(open('$CONFIG_FILE')); print(d.get('$1',''))" 2>/dev/null || true; }
  [[ -n "$(_cfg target)" ]]              && TARGET="$(_cfg target)"
  [[ -n "$(_cfg captureMethod)" ]]       && CAPTURE_METHOD="$(_cfg captureMethod)"
  [[ -n "$(_cfg deployCommand)" ]]       && DEPLOY_CMD="$(_cfg deployCommand)"
  [[ -n "$(_cfg maxIterations)" ]]       && MAX_ITERATIONS="$(_cfg maxIterations)"
  [[ -n "$(_cfg convergenceThreshold)" ]] && CONVERGENCE_THRESHOLD="$(_cfg convergenceThreshold)"
  _exp_enabled="$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(d.get('exploration',{}).get('enabled','false'))" 2>/dev/null || true)"
  [[ -n "$_exp_enabled" ]] && EXPLORATION_ENABLED="$_exp_enabled"
  _exp_count="$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(d.get('exploration',{}).get('count','10'))" 2>/dev/null || true)"
  [[ -n "$_exp_count" ]] && EXPLORATION_COUNT="$_exp_count"
  _figma="$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(d.get('exploration',{}).get('figmaFileKey',''))" 2>/dev/null || true)"
  [[ -n "$_figma" ]] && FIGMA_FILE_KEY="$_figma"
fi

RUN_ID="$(date '+%Y-%m-%d_%H-%M')"
START_TIME="$(date '+%Y-%m-%d %H:%M')"

# ─── Setup Directories ────────────────────────────────────────────────────────

mkdir -p "$AUTODESIGN_DIR/captures/baseline"
mkdir -p "$AUTODESIGN_DIR/captures/explorations"
mkdir -p "$AUTODESIGN_DIR/judges"
mkdir -p "$AUTODESIGN_DIR/logs"

# Initialize BRIEFING.md
if [[ ! -f "$AUTODESIGN_DIR/BRIEFING.md" ]]; then
  cat > "$AUTODESIGN_DIR/BRIEFING.md" <<EOF
# Autodesign Briefing — $RUN_ID

## Summary
In progress...

## Iterations
EOF
fi

# Initialize heartbeat
echo "$(date '+%H:%M:%S') | STARTING | setting up | iteration: 0/$MAX_ITERATIONS" > "$AUTODESIGN_DIR/HEARTBEAT"

# ─── Ensure .autodesign/ in .gitignore ───────────────────────────────────────

GITIGNORE="$PROJECT_ROOT/.gitignore"
if [[ -f "$GITIGNORE" ]] && ! grep -q '\.autodesign/' "$GITIGNORE" 2>/dev/null; then
  printf "\n# Autodesign agent data\n.autodesign/\n" >> "$GITIGNORE"
elif [[ ! -f "$GITIGNORE" ]]; then
  echo ".autodesign/" > "$GITIGNORE"
fi

# ─── Build Exploration Prompt ─────────────────────────────────────────────────

build_exploration_prompt() {
  cat <<PROMPT
@CLAUDE.md

You are the Autodesign Exploration agent. Your job is to generate $EXPLORATION_COUNT
distinct design explorations in Figma, then get cross-model consensus on which direction
to pursue. This is the "go wide" phase — diverge before converging.

PROJECT ROOT: $PROJECT_ROOT
AUTODESIGN DIR: $AUTODESIGN_DIR
FIGMA FILE KEY: ${FIGMA_FILE_KEY:-create a new Figma file}
TARGET: ${TARGET:-detect from project}
EXPLORATION COUNT: $EXPLORATION_COUNT

===================================================================
STEP 1: SET UP FIGMA
===================================================================

1. If FIGMA_FILE_KEY is set, open that Figma file via Figma MCP.
   Otherwise, create a new Figma file for this project.
2. Create a new Figma page called "Explorations" (do not disturb existing pages).
3. Note the file key for use in subsequent steps.

===================================================================
STEP 2: GENERATE $EXPLORATION_COUNT EXPLORATIONS
===================================================================

Create $EXPLORATION_COUNT distinct frames on the "Explorations" page. Name them:
  "Exploration 01", "Exploration 02", ... "Exploration $(printf '%02d' $EXPLORATION_COUNT)"

CRITICAL: These must be GENUINELY DIFFERENT — not $EXPLORATION_COUNT variations of
the same idea. Vary across all dimensions:
  - Layout structure: single column / grid / editorial / asymmetric / split-screen
  - Visual direction: minimal / rich / typographic / illustrative / photo-forward / data-forward
  - Tone: serious+professional / playful+friendly / bold+aggressive / calm+trustworthy / premium+exclusive
  - Typographic voice: display-led / body-text-led / oversized numerics / mono/code aesthetic
  - Color: monochrome / brand accent only / full palette / neutral+one pop / dark / light
  - Density: spacious and airy / information-dense / magazine-style / card-grid

If you notice yourself repeating a visual pattern, skip it and invent something different.
The goal is to surface the widest possible solution space before committing to a direction.

For each exploration:
1. Design it fully enough that it communicates the direction — not pixel-perfect,
   but enough to evaluate visual hierarchy, tone, and layout
2. Capture a screenshot: save to $AUTODESIGN_DIR/captures/explorations/exploration-$(printf '%02d' N).png

===================================================================
STEP 3: CLAUDE EVALUATION (you, now)
===================================================================

Review all $EXPLORATION_COUNT screenshots. For each, score 1-10 on:
  - Visual hierarchy: does the eye go where it should?
  - Distinctiveness: does it avoid generic AI design clichés?
  - Fit-for-purpose: does the visual direction match the product intent?
  - Polish potential: how much work to make this production-ready?

Compute a total score (max 40). Rank your top 3 picks with specific reasoning.
Write your evaluation to $AUTODESIGN_DIR/claude-exploration-review.md:

  # Claude Exploration Review
  ## Scores
  | Exploration | Hierarchy | Distinctiveness | Fit | Polish Potential | Total |
  |-------------|-----------|-----------------|-----|-----------------|-------|
  | 01          | 8         | 7               | 9   | 8               | 32    |
  ...
  ## Top 3
  1. Exploration XX — [reason]
  2. Exploration XX — [reason]
  3. Exploration XX — [reason]
  ## Discard
  - Exploration XX — [reason]

===================================================================
STEP 4: CODEX EVALUATION (cross-model)
===================================================================

Run Codex to independently evaluate the same explorations:

  codex exec \
    -c model_reasoning_effort="xhigh" \
    "You are evaluating $EXPLORATION_COUNT UI design explorations. Screenshots are in:
     $AUTODESIGN_DIR/captures/explorations/

     Score each design 1-10 on:
     - Visual hierarchy (does the eye go where it should?)
     - Distinctiveness (avoids generic AI design clichés?)
     - Fit-for-purpose (visual direction matches product intent?)
     - Polish potential (how close is this to production-ready?)

     Rank your top 3 with specific reasoning. Also list any you'd eliminate.
     Output format: write a markdown file with a scores table and top 3 list." \
    > $AUTODESIGN_DIR/codex-exploration-review.md 2>&1

===================================================================
STEP 5: SYNTHESIZE CONSENSUS
===================================================================

Compare your evaluation with Codex's:
1. Find designs that appear in BOTH top-3 lists → consensus picks
2. Rank by combined score (your score + codex score)
3. If no consensus: list top 2 from each model separately

Write the shortlist to $AUTODESIGN_DIR/exploration-shortlist.md:

  # Exploration Shortlist
  ## Consensus Top 3
  1. Exploration XX (avg score: N) — [combined reasoning]
  2. Exploration XX (avg score: N) — [combined reasoning]
  3. Exploration XX (avg score: N) — [combined reasoning]

  ## Claude-only picks (if no consensus)
  - Exploration XX — [reason]

  ## Codex-only picks (if no consensus)
  - Exploration XX — [reason]

  ## Recommendation
  [1-2 sentences: which direction to pursue and why]

===================================================================
STEP 6: LABEL FIGMA
===================================================================

In Figma, organize the Explorations page into a Section labeled "Round 1".
Add a small annotation below each frame with its score and key characteristics.
Do NOT delete any exploration frames.

===================================================================
SIGNALS
===================================================================

When complete, output exactly one of:
  <promise>EXPLORATION_DONE:XX</promise>  — replace XX with the recommended exploration number
  <promise>BLOCKED:reason</promise>       — if you cannot proceed
PROMPT
}

# ─── Build Iteration Prompt ───────────────────────────────────────────────────

build_iteration_prompt() {
  local iteration="$1"
  local prev_iteration=$((iteration - 1))
  local captures_dir="$AUTODESIGN_DIR/captures/iteration-$iteration"
  local prev_captures="$AUTODESIGN_DIR/captures/iteration-$prev_iteration"
  [[ "$prev_iteration" -eq 0 ]] && prev_captures="$AUTODESIGN_DIR/captures/baseline"

  cat <<PROMPT
@CLAUDE.md

You are the Autodesign Iteration agent. You are running iteration $iteration of $MAX_ITERATIONS.
Each iteration you evaluate the current design state, implement improvements, and save to Figma.

PROJECT ROOT: $PROJECT_ROOT
AUTODESIGN DIR: $AUTODESIGN_DIR
TARGET: ${TARGET:-detect from project}
CAPTURE METHOD: $CAPTURE_METHOD
DEPLOY COMMAND: ${DEPLOY_CMD:-none}
ITERATION: $iteration / $MAX_ITERATIONS
FIGMA FILE KEY: ${FIGMA_FILE_KEY:-check config.json}

===================================================================
HEARTBEAT (CRITICAL — DO THROUGHOUT)
===================================================================

Write to $AUTODESIGN_DIR/HEARTBEAT after every significant action:
  echo "TIMESTAMP | ITERATION $iteration/$MAX_ITERATIONS | STEP: description" > $AUTODESIGN_DIR/HEARTBEAT

===================================================================
STEP 1: READ PRIOR CONTEXT
===================================================================

1. Read $AUTODESIGN_DIR/BRIEFING.md — understand what's been done so far
2. Read $AUTODESIGN_DIR/judges/ — load all judge prompts
3. Read $AUTODESIGN_DIR/eval-gaps.md if it exists
4. If iteration > 1: read previous captures at $prev_captures/ to understand prior state

===================================================================
STEP 2: CAPTURE CURRENT STATE
===================================================================

Capture screenshots of the current design across all configured viewports.
Save to $captures_dir/:
  desktop.png (1440x900)
  mobile.png  (390x844)
  [additional viewports from config]

Capture method: $CAPTURE_METHOD
  - playwright: npx playwright screenshot --viewport-size=WxH --full-page $TARGET output.png
  - chrome-mcp: use mcp__claude-in-chrome__resize_window + mcp__claude-in-chrome__computer screenshot
  - figma:      use Figma MCP to get_screenshot of the current design frame

===================================================================
STEP 3: RUN DESIGN EVAL STACK
===================================================================

TIER 1 — /critique (blocking)
Run the /critique skill on the current screenshots. Get prioritized findings:
  CRITICAL | HIGH | MEDIUM | LOW — each with a concrete fix recommendation

TIER 2 — Targeted impeccable skills (blocking for CRITICAL findings)
Based on /critique findings, select 1-3 most relevant skills:
  /typeset    — typography issues
  /arrange    — layout and spacing issues
  /colorize   — color and contrast issues
  /clarify    — copy and label issues
  /distill    — over-designed, needs simplification
  /bolder     — too safe, needs more impact
  /quieter    — too aggressive, needs toning down
  /animate    — missing motion or microinteractions
  /harden     — error states and edge cases
  /adapt      — responsive and cross-device issues
  /polish     — alignment, consistency, final details
  /delight    — missing personality and joy
  /onboard    — first-time UX and empty states
  /normalize  — design system inconsistency
  /overdrive  — ambitious visual effects

Run each selected skill and collect specific, actionable recommendations.

TIER 3 — Design judges (from $AUTODESIGN_DIR/judges/)
Run each judge as a sub-agent with the screenshots. Each returns:
  <eval>PASS</eval> or <eval>FAIL: reason</eval>

TIER 4 — Cross-model consensus (advisory)
  codex exec \
    -c model_reasoning_effort="xhigh" \
    "Review the UI screenshots at $captures_dir/ for design quality.
     Focus on: visual hierarchy, consistency, mobile experience, AI slop, polish.
     Return findings as: CRITICAL: [issue] FIX: [fix] / HIGH: ... / MEDIUM: ...
     Only flag issues you are confident about." \
    > $AUTODESIGN_DIR/codex-iter-$iteration-review.md 2>&1

  Compare with /critique findings. Only act on consensus findings, or CRITICAL from either.

===================================================================
STEP 4: PRIORITIZE AND IMPLEMENT
===================================================================

1. Merge all findings. Deduplicate. Sort: CRITICAL > HIGH > MEDIUM > LOW.
2. Select top 3-5 fixes for this iteration. Skip LOW unless nothing else.
3. Implement each fix in source code. Note what changed and why.
4. Run feedback commands if configured (typecheck, lint, etc.)

===================================================================
STEP 5: VERIFY
===================================================================

1. Re-capture screenshots after implementation
2. Quick-check: did the fix work? Any regressions?
3. If regression: revert that specific fix, note it in BRIEFING.md

===================================================================
STEP 6: UPDATE FIGMA (preserve history)
===================================================================

1. Open the Figma file (key: $FIGMA_FILE_KEY)
2. On the "Iterations" page (create if it doesn't exist):
   - Copy the current design as a new frame
   - Name it: "v$iteration — [key change summary]"
   - Position it to the RIGHT of the previous iteration frame (100px gap)
   - Add a small annotation below: date + top 2-3 eval findings that drove this change
3. Update the "Final" page (create if it doesn't exist):
   - Replace the previous frame with the latest design
   - Name it: "Final"
4. NEVER delete or overwrite existing iteration frames

===================================================================
STEP 7: DEPLOY (if configured)
===================================================================

If DEPLOY_CMD is set:
  ${DEPLOY_CMD:-skip}
Wait for deployment to propagate before re-capturing.

===================================================================
STEP 8: COMMIT
===================================================================

Stage specific changed files (NOT git add .). Commit:
  Subject: design(iter-$iteration): [key change]
  Body: what changed, why, eval findings that drove it

Push to remote.

===================================================================
STEP 9: UPDATE BRIEFING
===================================================================

Append to $AUTODESIGN_DIR/BRIEFING.md:

  ## Iteration $iteration — $(date '+%Y-%m-%d %H:%M')
  **Key changes:** [list fixes]
  **Eval results:** [judge pass/fail, codex consensus]
  **Remaining:** [unfixed issues]

Update $AUTODESIGN_DIR/HEARTBEAT:
  echo "$(date '+%H:%M:%S') | ITERATION $iteration/$MAX_ITERATIONS | COMPLETE | [summary]" > $AUTODESIGN_DIR/HEARTBEAT

===================================================================
STEP 10: CONVERGENCE CHECK
===================================================================

Check whether the design has converged:
- /critique returned 0 CRITICAL and 0 HIGH findings
- All judges returned PASS

If converged: output <promise>CONVERGED</promise>
If not converged but fixes remain: output <promise>CONTINUE</promise>
If blocked: output <promise>BLOCKED:reason</promise>
PROMPT
}

# ─── Display Banner ───────────────────────────────────────────────────────────

echo "╔══════════════════════════════════════════════════════╗"
echo "║              AUTODESIGN DISPATCHER                  ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Project:      $PROJECT_ROOT"
echo "║  Target:       ${TARGET:-not set}"
echo "║  Capture:      $CAPTURE_METHOD"
echo "║  Runtime:      $AGENT_RUNTIME"
echo "║  Exploration:  $EXPLORATION_ENABLED (count: $EXPLORATION_COUNT)"
echo "║  Max iter:     $MAX_ITERATIONS"
echo "║  Convergence:  $CONVERGENCE_THRESHOLD consecutive clean passes"
echo "║  Run ID:       $RUN_ID"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ─── Run Agent ────────────────────────────────────────────────────────────────

run_agent() {
  local prompt="$1"
  local log_file="$2"
  local output=""

  local prompt_file
  prompt_file="$(mktemp)"
  echo "$prompt" > "$prompt_file"

  if [[ "$AGENT_RUNTIME" == "claude" ]]; then
    output="$(cd "$PROJECT_ROOT" && env -u CLAUDECODE claude -p --dangerously-skip-permissions \
      --max-turns 80 \
      < "$prompt_file" 2>&1)" || true
  else
    output="$(cd "$PROJECT_ROOT" && codex exec --dangerously-bypass-approvals-and-sandbox \
      "$(cat "$prompt_file")" 2>&1)" || true
  fi

  rm -f "$prompt_file"
  echo "$output" >> "$log_file"
  echo "$output"
}

# ─── Phase 1.5: Exploration ───────────────────────────────────────────────────

SELECTED_EXPLORATION=""

if [[ "$EXPLORATION_ENABLED" == "true" ]]; then
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  EXPLORATION PHASE — generating $EXPLORATION_COUNT designs"
  echo "  $(date '+%Y-%m-%d %H:%M:%S')"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  EXPLORATION_PROMPT="$(build_exploration_prompt)"
  EXPLORATION_OUTPUT="$(run_agent "$EXPLORATION_PROMPT" "$AUTODESIGN_DIR/logs/exploration.log")"

  echo ""
  if [[ -f "$AUTODESIGN_DIR/HEARTBEAT" ]]; then
    echo "  HEARTBEAT: $(cat "$AUTODESIGN_DIR/HEARTBEAT")"
  fi
  echo ""

  if echo "$EXPLORATION_OUTPUT" | grep -qE '<promise>EXPLORATION_DONE:'; then
    SELECTED_EXPLORATION="$(echo "$EXPLORATION_OUTPUT" | grep -oE '<promise>EXPLORATION_DONE:[0-9]+</promise>' | grep -oE '[0-9]+')"
    echo "=== Exploration complete. Selected: Exploration $SELECTED_EXPLORATION ==="
    echo ""
    echo "Review the shortlist at: $AUTODESIGN_DIR/exploration-shortlist.md"
    echo ""
    echo "Press ENTER to continue with the deep iteration loop, or Ctrl+C to stop and review."
    read -r
  elif echo "$EXPLORATION_OUTPUT" | grep -qF "<promise>BLOCKED:"; then
    echo "=== EXPLORATION BLOCKED. Check $AUTODESIGN_DIR/logs/exploration.log ==="
    exit 1
  else
    echo "WARNING: exploration phase did not emit a clear signal."
    echo "Check $AUTODESIGN_DIR/logs/exploration.log"
    echo "Press ENTER to continue anyway, or Ctrl+C to stop."
    read -r
  fi
fi

# ─── Phase 2: Deep Iteration Loop ────────────────────────────────────────────

ITERATION=0
CONSECUTIVE_CONVERGED=0
FAILURES=0

while [[ "$ITERATION" -lt "$MAX_ITERATIONS" ]]; do
  ITERATION=$((ITERATION + 1))
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  ITERATION $ITERATION / $MAX_ITERATIONS"
  echo "  $(date '+%Y-%m-%d %H:%M:%S')"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  mkdir -p "$AUTODESIGN_DIR/captures/iteration-$ITERATION"

  ITER_PROMPT="$(build_iteration_prompt "$ITERATION")"
  ITER_OUTPUT="$(run_agent "$ITER_PROMPT" "$AUTODESIGN_DIR/logs/iteration-$ITERATION.log")"

  echo ""
  if [[ -f "$AUTODESIGN_DIR/HEARTBEAT" ]]; then
    echo "  HEARTBEAT: $(cat "$AUTODESIGN_DIR/HEARTBEAT")"
  fi
  echo ""

  if echo "$ITER_OUTPUT" | grep -qF "<promise>CONVERGED</promise>"; then
    CONSECUTIVE_CONVERGED=$((CONSECUTIVE_CONVERGED + 1))
    echo "  Converged pass $CONSECUTIVE_CONVERGED / $CONVERGENCE_THRESHOLD"
    if [[ "$CONSECUTIVE_CONVERGED" -ge "$CONVERGENCE_THRESHOLD" ]]; then
      echo ""
      echo "=== AUTODESIGN CONVERGED after $ITERATION iterations ==="
      break
    fi
  else
    CONSECUTIVE_CONVERGED=0
  fi

  if echo "$ITER_OUTPUT" | grep -qF "<promise>BLOCKED:"; then
    echo ""
    echo "=== BLOCKED. Check $AUTODESIGN_DIR/logs/iteration-$ITERATION.log ==="
    echo "Sleeping 5 minutes before retry..."
    sleep 300
    ITERATION=$((ITERATION - 1))  # retry this iteration
    continue
  fi

  if [[ -z "$ITER_OUTPUT" ]]; then
    FAILURES=$((FAILURES + 1))
    echo "WARNING: Empty output (failure #$FAILURES)"
    if [[ "$FAILURES" -ge 3 ]]; then
      echo "ERROR: 3 consecutive failures, stopping"
      break
    fi
  else
    FAILURES=0
  fi

  sleep 10
done

# ─── Handoff ──────────────────────────────────────────────────────────────────

END_TIME="$(date '+%Y-%m-%d %H:%M')"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              AUTODESIGN COMPLETE                    ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Iterations:   $ITERATION"
echo "║  Started:      $START_TIME"
echo "║  Ended:        $END_TIME"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "Review:"
echo "  Briefing:     $AUTODESIGN_DIR/BRIEFING.md"
echo "  Captures:     $AUTODESIGN_DIR/captures/"
echo "  Logs:         $AUTODESIGN_DIR/logs/"
if [[ "$EXPLORATION_ENABLED" == "true" ]]; then
  echo "  Shortlist:    $AUTODESIGN_DIR/exploration-shortlist.md"
fi
echo ""
